services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html

networks:
  app-network:
    driver: bridge