# Generated by Django 5.1.3 on 2024-11-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ponguser_two_factor_enabled_alter_ponguser_id_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
