# Generated by Django 5.1.3 on 2024-11-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_ponguser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
