# Generated by Django 5.1.3 on 2024-11-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_ponguser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponguser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
