# Generated by Django 5.1.3 on 2024-11-29 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_ponguser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponguser',
            name='avatar',
            field=models.ImageField(default='avatars', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='ponguser',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ponguser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
