# Generated by Django 5.1.3 on 2024-11-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_ponguser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponguser',
            old_name='two_factor_enabled',
            new_name='twoFactorEnabled',
        ),
        migrations.AddField(
            model_name='ponguser',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
