# Generated by Django 5.1.3 on 2024-12-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_two_factor_enabled_ponguser_twofactorenabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponguser',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
