# Generated by Django 5.1.3 on 2024-11-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_ponguser_avatar_ponguser_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponguser',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
