# Generated by Django 5.1.3 on 2024-11-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_ponguser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponguser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
