# Generated by Django 5.1.3 on 2024-11-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_ponguser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponguser',
            name='display_name',
        ),
        migrations.AddField(
            model_name='ponguser',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ponguser',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='ponguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
