# Generated by Django 5.1.3 on 2024-11-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_ponguser_display_name_ponguser_online_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponguser',
            old_name='online_status',
            new_name='onlineStatus',
        ),
        migrations.RenameField(
            model_name='ponguser',
            old_name='two_factor_enabled',
            new_name='twoFactorEnabled',
        ),
        migrations.AddField(
            model_name='ponguser',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ponguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
